export const NETWORKS: any = {
  mainnet: {
    coin: "ML",
    network: "MAINNET",
    displayName: "Mainnet",
    domain: "explorer.mintlayer.org",
    api: "api-server.mintlayer.org",
    matchers: {
      block: /^[0-9]+$/,
      blockHash: /^[0-9a-fA-F]{64}$/,
      tx: /^0?x?[0-9a-fA-F]{64}$/,
      address: /^mm?tc1[a-zA-Z0-9]{40}$/,
      pool: /^mpool1[a-zA-Z0-9]{58}$/,
      delegation: /^mdelg1[a-zA-Z0-9]{58}$/,
      token: /^mmltk1[a-zA-Z0-9]{58}$/,
      tokenName: /^[a-zA-Z0-9_]+$/,
    },
  },
  testnet: {
    coin: "TML",
    network: "TESTNET",
    displayName: "Testnet",
    domain: "lovelace.explorer.mintlayer.org",
    api: "api-server-lovelace.mintlayer.org",
    matchers: {
      block: /^[0-9]+$/,
      blockHash: /^[0-9a-fA-F]{64}$/,
      tx: /^0?x?[0-9a-fA-F]{64}$/,
      address: /^tmtc?1[a-zA-Z0-9]{40}$/,
      pool: /^tpool1[a-zA-Z0-9]{58}$/,
      delegation: /^tdelg1[a-zA-Z0-9]{58}$/,
      token: /^tmltk1[a-zA-Z0-9]{58}$/,
      tokenName: /^[a-zA-Z0-9_]+$/,
    },
  },
};
